use_frameworks!

target 'finaltest_Example' do
  pod 'finaltest', :path => '../'

  target 'finaltest_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
